import 'dotenv/config';
import express from 'express';
import cors from 'cors';
import dotenv from 'dotenv';
import { router as auth } from './routes/auth.js';
import { router as games } from './routes/games.js';
import { router as users } from './routes/users.js';
import { router as reviews } from './routes/reviews.js';
import { router as purchases } from './routes/purchases.js';
import { router as achievements } from './routes/achievements.js';
import { router as awards } from './routes/awards.js';
dotenv.config();
const app = express();
app.use(cors({ origin: 'http://localhost:5173', credentials: true }));
app.use(express.json());
app.get('/api/health', (_req,res)=>res.json({ ok:true }));
app.use('/api/auth', auth);
app.use('/api/games', games);
app.use('/api/users', users);
app.use('/api/reviews', reviews);
app.use('/api/purchases', purchases);
app.use('/api/achievements', achievements);
app.use('/api/awards', awards);
const port = process.env.PORT || 5174;
app.listen(port, () => console.log(`API listening on http://localhost:${port}`));